name: "ClamAV Web Client"
slug: "clamav_web_client"
version: "0.1.3"
description: "Web UI client for ClamAV, connecting to an existing clamd service."
url: "https://hub.docker.com/r/rguziy/clamav-web-client"

arch:
  - amd64

startup: "services"
boot: "auto"

webui: "http://[HOST]:[PORT:8080]/"

ports:
  "8080/tcp": 8082
ports_description:
  "8080/tcp": "ClamAV Web Client UI"

hassio_api: false
homeassistant_api: false

environment:
  CLAMAV_HOST: "192.168.68.73"
  CLAMAV_PORT: "3310"

options: {}
schema: {}
